version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8010:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - app_network
    depends_on:
      - db
      - chromadb
      - minio

  frontend:
    build: ./frontend
    ports:
      - "3010:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://rag-web-ui-hnxxba-59a90c-132-226-114-206.traefik.me
    networks:
      - app_network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ragwebui
      - MYSQL_USER=ragwebui
      - MYSQL_PASSWORD=ragwebui
      - TZ=Asia/Shanghai
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8011:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app_network

  # For Qdrant, Remove the comment and run the following command to start the service
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6343:6333" # REST API
  #     - "6344:6334" # GRPC
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   environment:
  #     - QDRANT_ALLOW_RECOVERY_MODE=true
  #   networks:
  #     - app_network

  minio:
    image: minio/minio:latest
    ports:
      - "9010:9000" # API port
      - "9011:9001" # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network

volumes:
  mysql_data:
  chroma_data:
  minio_data:
  # qdrant_data:

networks:
  app_network:
    driver: bridge